spring:
  application:
    name: eureka-server-pb
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka
    fetch-registry: false
server:
  port: 8761
